import { describe, expect, it } from "vitest";

import {
  inferSectionConfidence,
  parseSoulMarkdownSections,
  parseSoulDocTitle,
  clipAssistantTranscriptSnippet,
  extractSoulSubtitleLine,
} from "@/lib/grill-me/soul-section-parser";

describe("parseSoulMarkdownSections", () => {
  it("splits numbered ## headings into sections", () => {
    const md = `# X\n\n## 1. Identity\nOne\n\n## 2. Problem\nTwo\n`;
    const s = parseSoulMarkdownSections(md);
    expect(s).toHaveLength(2);
    expect(s[0].num).toBe(1);
    expect(s[0].slug).toBe("soul-section-1");
    expect(s[0].title).toBe("Identity");
    expect(s[0].markdown).toContain("## 1.");
    expect(s[1].num).toBe(2);
  });
});

describe("inferSectionConfidence", () => {
  it("detects UNKNOWN", () =>
    expect(inferSectionConfidence("foo [UNKNOWN — bar")).toBe("unknown"));
  it("detects HYPOTHESIS", () =>
    expect(inferSectionConfidence("x [HYPOTHESIS] y")).toBe("hypothesis"));
  it("defaults to validated", () =>
    expect(inferSectionConfidence("Solid paragraph text.")).toBe("validated"));
});

describe("extractSoulSubtitleLine", () => {
  it("extracts italic meta after title", () => {
    expect(
      extractSoulSubtitleLine(
        `# X\n\n*Generated by Grill-Me · 2026-05-02 · Version 1.0*`,
      ),
    ).toContain("Generated by Grill-Me");
  });
});

describe("parseSoulDocTitle", () => {
  it("uses first markdown h1 else fallback", () => {
    expect(parseSoulDocTitle("# Acme — Soul Document\n\nx", "Acme")).toBe(
      "Acme — Soul Document",
    );
    expect(parseSoulDocTitle("", "Bee")).toBe("Bee — Soul Document");
  });
});

describe("clipAssistantTranscriptSnippet", () => {
  it("strips markdown fenced soul", () =>
    expect(
      clipAssistantTranscriptSnippet(`Hello\n\n\`\`\`markdown\n# doc\n`),
    ).toContain("Hello"));
});
