import { describe, expect, it } from "vitest";

import {
  inferSectionConfidence,
  parseSoulMarkdownSections,
  parseSoulDocTitle,
  clipAssistantTranscriptSnippet,
  extractSoulSubtitleLine,
  formatSoulNavGapSummary,
  truncateAppendedSoulDocumentDuplicate,
  decodeSoulNavTitle,
} from "@/lib/grill-me/soul-section-parser";

describe("parseSoulMarkdownSections", () => {
  it("splits numbered ## headings into sections", () => {
    const md = `# X\n\n## 1. Identity\nOne\n\n## 2. Problem\nTwo\n`;
    const s = parseSoulMarkdownSections(md);
    expect(s).toHaveLength(2);
    expect(s[0].num).toBe(1);
    expect(s[0].slug).toBe("soul-section-1-0");
    expect(s[0].title).toBe("Identity");
    expect(s[0].markdown).toContain("## 1.");
    expect(s[1].num).toBe(2);
    expect(s[1].slug).toBe("soul-section-2-1");
  });

  it("treats numbered ### as a section (AI sometimes uses h3)", () => {
    const md = "### 1. Identity\nA\n### 2. Offer\nB\n";
    const s = parseSoulMarkdownSections(md);
    expect(s).toHaveLength(2);
    expect(s[0].num).toBe(1);
    expect(s[0].title).toBe("Identity");
    expect(s[1].num).toBe(2);
  });

  it("gives unique slugs when ## 1. appears twice (duplicate paste)", () => {
    const md = "## 1. Identity\nA\n## 1. Identity\nB\n";
    const s = parseSoulMarkdownSections(md);
    expect(s).toHaveLength(2);
    expect(s[0].slug).toBe("soul-section-1-0");
    expect(s[1].slug).toBe("soul-section-1-1");
  });

  it("preserves leading zeros in section slug for scroll targets", () => {
    const md = `## 01. First\nBody\n`;
    const s = parseSoulMarkdownSections(md);
    expect(s[0]?.slug).toBe("soul-section-01-0");
  });
});

describe("inferSectionConfidence", () => {
  it("detects UNKNOWN", () =>
    expect(inferSectionConfidence("foo [UNKNOWN — bar")).toBe("unknown"));
  it("detects HYPOTHESIS", () =>
    expect(inferSectionConfidence("x [HYPOTHESIS] y")).toBe("hypothesis"));
  it("defaults to validated", () =>
    expect(inferSectionConfidence("Solid paragraph text.")).toBe("validated"));
});

describe("extractSoulSubtitleLine", () => {
  it("extracts italic meta after title", () => {
    expect(
      extractSoulSubtitleLine(
        `# X\n\n*Generated by Grill-Me · 2026-05-02 · Version 1.0*`,
      ),
    ).toContain("Generated by Grill-Me");
  });
});

describe("parseSoulDocTitle", () => {
  it("uses first markdown h1 else fallback", () => {
    expect(parseSoulDocTitle("# Acme — Soul Document\n\nx", "Acme")).toBe(
      "Acme — Soul Document",
    );
    expect(parseSoulDocTitle("", "Bee")).toBe("Bee — Soul Document");
  });
});

describe("formatSoulNavGapSummary", () => {
  it("lists sections that are not validated", () => {
    const md = `## 1. A\nSolid.\n\n## 2. B\n[HYPOTHESIS] guess\n\n## 3. C\n[UNKNOWN — x]\n`;
    const s = formatSoulNavGapSummary(md);
    expect(s).toContain("2. B");
    expect(s).toContain("hypothesis");
    expect(s).toContain("3. C");
    expect(s).toContain("unknown");
    expect(s).not.toContain("1. A");
  });
});

describe("truncateAppendedSoulDocumentDuplicate", () => {
  it("removes a second full copy starting at duplicate ## 1.", () => {
    const first =
      "## 1. A\nx\n## 2. B\ny\n## 3. C\nz\n";
    const doubled = `${first}\n${first}`;
    expect(truncateAppendedSoulDocumentDuplicate(doubled)).toBe(first.trimEnd());
  });

  it("does not truncate two early ## 1. with no full run between", () => {
    const md = "## 1. A\n## 1. B\n";
    expect(truncateAppendedSoulDocumentDuplicate(md)).toBe(md);
  });
});

describe("decodeSoulNavTitle", () => {
  it("decodes basic entities in headings", () => {
    expect(decodeSoulNavTitle("P &amp; Q")).toBe("P & Q");
  });
});

describe("clipAssistantTranscriptSnippet", () => {
  it("strips markdown fenced soul", () =>
    expect(
      clipAssistantTranscriptSnippet(`Hello\n\n\`\`\`markdown\n# doc\n`),
    ).toContain("Hello"));
});